### ISSUE TITLE
Plugin not installed properly?

### ISSUE THREAD

**Issue by MARCxGAMBIT** [MonaDevAI/AI-Developer-Plugin-for-Eclipse#5]
I have the following Eclipse version

Version: 2023-09 (4.29.0)
Build id: 20230907-1323

And the following Java

openjdk 17.0.8.1 2023-08-24 LTS
OpenJDK Runtime Environment SapMachine (build 17.0.8.1+1-LTS)
OpenJDK 64-Bit Server VM SapMachine (build 17.0.8.1+1-LTS, mixed mode, sharing)

After installing the AI Plugin (several times) and restarting Eclipse (several times) I still don't see "AIDev Tools" in Window > Preferences and also the new icon is not available in the toolbar

![image](https://github.com/MonaDevAI/AI-Developer-Plugin-for-Eclipse/assets/147161757/f5d4b6bc-8dd7-4ebf-8c60-ef974cb054e4)

**Comment by MonaDevAI** [comment]
Thanks for trying this out. In your eclipse, please ensure you have this version installed. I have mentioned in the step-by-step document.
  JustJ Adoptium OpenJDK Hotspot JRE Complete	21.0.0.v20231013-1207	
Go to Help > Install New Software
https://download.eclipse.org/justj/jres/latest
