### ISSUE TITLE
How can we get the URL , Deployment and Key

### ISSUE THREAD

**Issue by samrulesusa** [MonaDevAI/AI-Developer-Plugin-for-Eclipse#6]
![Screenshot 2023-10-26 110750](https://github.com/MonaDevAI/AI-Developer-Plugin-for-Eclipse/assets/48501362/39d4766a-d3f0-4140-a70d-1d684de90e2d)

**Comment by MonaDevAI** [comment]
hi,

You need to get an azure openai subscription. 
https://azure.microsoft.com/en-us/free/ai-services/

**Comment by samrulesusa** [comment]
Thank you , I was able to subscribe to the open AI service and was able to generate the code.

**Comment by MonaDevAI** [comment]
Thanks. Please share your feedback.

**Comment by bmaciag** [comment]
Hi, I created a Azure OpenAI ressource. I can also see the Endpoint and Key 1 and Key 2 in the Azure dashboard. But where to find the value to place into deployment? And second question, should I use Key 1 or Key 2?

**Comment by MonaDevAI** [comment]
Thanks @samrulesusa .

Regarding deployment. Go to Azure Open AI Studio. Create new deployment and use the same in the preference.
![image](https://github.com/microsoft/AI-Developer-Plugin-for-Eclipse/assets/147940300/24ecd6c5-c83b-4dfe-bab9-48daadc90c3d)
![image](https://github.com/microsoft/AI-Developer-Plugin-for-Eclipse/assets/147940300/c5e93abd-17bd-4696-9ecb-6c8555c0b465)
