### ISSUE TITLE
Azure Credentials don't get saved

### ISSUE THREAD

**Issue by MARCxGAMBIT** [MonaDevAI/AI-Developer-Plugin-for-Eclipse#7]
Hey, after entering the endpoint, deployment, key and template folder and clicking "Apply" or "Apply and close" code completion doesn't do anything. So after checking the preferences again I noticed that the fields (endpoint, deployment, key, template) are empty again. What could be the issue here?

**Comment by MonaDevAI** [comment]
Wanted to check few things to understand the issue.
1-confirm if you have used aidttools.zip file provided here-> https://github.com/MonaDevAI/AI-Developer-Plugin-for-Eclipse
![image](https://github.com/MonaDevAI/AI-Developer-Plugin-for-Eclipse/assets/147940300/5b9eccff-a83c-4127-b3d9-4baa770bdbff)

2-Go to Windows -> Preference-> General->Security-> Secure Storage . Check if you can see following
![image](https://github.com/MonaDevAI/AI-Developer-Plugin-for-Eclipse/assets/147940300/7c18dc34-30de-4e16-9d77-bebaad4bfc68)
3-Go to Help->Install New Software->What is already installed-> confirm if you exactly see the same in the installation: MSFTPlatform AIDT Tools for Eclipse 1.0.0
![image](https://github.com/MonaDevAI/AI-Developer-Plugin-for-Eclipse/assets/147940300/de6cd615-507c-44d5-b8fe-c6246f39b86d)

**Comment by MARCxGAMBIT** [comment]
I think I used the stuff that was published here

https://github.com/MonaDevAI/AI-Developer-Plugin-for-Eclipse/releases

With your provided ZIP file it works.

**Comment by MonaDevAI** [comment]
Thanks for confirming.
